version: "3.3"

services:
  db:
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/.db
    restart: unless-stopped

  nextjs:
    container_name: nextjs
    ports:
      - 3000:3000
    build:
      context: services/nextjs
      dockerfile: Dockerfile
    command: bash -c "yarn dev"
    volumes:
      - .:/app
    env_file:
      - .env/.nextjs
    depends_on:
      - db

volumes:
  postgres_data:
